---
title: "Developing New Network Functions and Network Statistics for `netjack`"
author: "Teague Henry"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{developingNetjack}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignettes outlines how to develop custom _network manipulation functions_ and _network statistic functions_ for the `netjack` package. `netjack` was designed to be an easily extendible framework for working with large sets of networks, and the two entry points for custom development are:

- Functions that change networks
- Functions that calculate network statistics

We will go through how to develop custom functions now. This  


###Network Manipulation Functions

A custom network manipulation function takes as its argument a `Net` object and any additional arguments for the procedure, and returns a named list of `Net` objects. For example, this is the function to perform the node jackknife procedure. This removes each node from the network in turn, and produces a list of `Net` objects, each named for the node that has been removed.

```

node_jackknife = function(Net){

  toReturn = list()

  for(i in 1:dim(Net@net)[[1]]){
    toReturn[[i]] = methods::new("Net", net = Net@net[-i,-i],
                        net.name = Net@net.name,
                        node.variables = lapply(Net@node.variables, function(x, i){
                          return(x[-i])
                        }, i = i))
  }
  names(toReturn) = as.character(1:dim(Net@net)[[1]])
  return(toReturn)
}


```
